---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: i-see-dead-pods
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 15
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      type: cronjob
      cronjob:
        schedule: "* * * * *"
        ttlSecondsAfterFinished: 60
      restartPolicy: OnFailure
      concurrencyPolicy: Forbid
      successfulJobsHistoryLimit: 1
      failedJobsHistoryLimit: 1
    image:
      repository: ghcr.io/k8s-at-home/kubectl
      tag: v1.25.4
    command:
      - /bin/sh
      - -ec
      - |
        kubectl get pods \
          --all-namespaces \
          -o go-template \
          --template='{{range .items}}{{printf "%s %s %s\n" .metadata.namespace .metadata.name .status.message}}{{end}}' \
          | grep "Pod was terminated in response to imminent node shutdown." \
          | awk '{print $1, $2}' \
          | xargs -n2 kubectl delete pod -n || true
    resources:
      requests:
        cpu: 10m
        memory: 10Mi
      limits:
        memory: 10Mi
