---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Schedule - Renovate

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: Dry-Run
        default: "null"
        required: false
      logLevel:
        description: Log-Level
        default: debug
        required: false
  schedule:
    - cron: "0 */6 * * *"
  push:
    branches:
      - main
    paths:
      - .github/renovate.json5
      - .github/renovate-bot.json5
      - .github/renovate/**.json5
      - .github/workflows/schedule-renovate.yaml

permissions:
  contents: read

concurrency:
  group: renovate
  cancel-in-progress: false

env:
  LOG_LEVEL: debug
  RENOVATE_DRY_RUN: false
  RENOVATE_CONFIG_FILE: .github/renovate-bot.json5

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/create-github-app-token
      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: "${{ secrets.BOT_APP_CLIENT_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      # https://github.com/marketplace/actions/checkout
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: "${{ steps.app-token.outputs.token }}"
          persist-credentials: false

      - name: Override default config from dispatch variables
        env:
          INPUT_DRY_RUN: ${{ github.event.inputs.dryRun }}
          INPUT_LOG_LEVEL: ${{ github.event.inputs.logLevel }}
        run: |
          echo "RENOVATE_DRY_RUN=${INPUT_DRY_RUN:-${RENOVATE_DRY_RUN}}" >> "${GITHUB_ENV}"
          echo "LOG_LEVEL=${INPUT_LOG_LEVEL:-${LOG_LEVEL}}" >> "${GITHUB_ENV}"

      # https://github.com/marketplace/actions/renovate-bot-github-action
      - name: Renovate
        uses: renovatebot/github-action@6d26fcf0275dc65624cbc3d51fe78bc773f98321 # v46.3.6
        with:
          configurationFile: "${{ env.RENOVATE_CONFIG_FILE }}"
          token: "${{ steps.app-token.outputs.token }}"
        env:
          RENOVATE_PRINT_CONFIG: "true"
